#!/bin/bash
# Compile and set up the code ready to run in a separate directory
# usage:  ./make2dgp 

#Change to code dir
origdir=${PWD}
pushd $GP2DSOURCELOC
#Compile.
make
#Setup dir
#if [ $? == 0 ]; then
mv gp $origdir
mv *.mod $origdir
cp makemovie.sh $origdir
#fi
make clean
#go back
popd
