#!/bin/bash
# Compile and set up the code ready to run in a separate directory
# usage:  ./make2dgp 

#Take care of any params.in changes
if [ -a params.in ]; then
	cp params.in $GP2DSOURCELOC
fi
#Change to code dir
origdir=${PWD}
pushd $GP2DSOURCELOC
#Compile.
make
#Setup dir
#if [ $? == 0 ]; then
mv gp $origdir
mv *.mod $origdir
cp makemovie.sh params.in $origdir
#fi
make clean
#go back
popd
